import type { ElementType } from "react";
import { FLEX_DEFAULT_ELEMENT } from "@/components/ui/Flex/constants.ts";
import {
    ALIGN_ITEMS,
    ALIGN_SELF,
    DISPLAY,
    FLEX_DIRECTION,
    FLEX_GROW,
    FLEX_SHRINK,
    FLEX_WRAP,
    GAP,
    JUSTIFY_CONTENT,
    LG_ALIGN_ITEMS,
    LG_DISPLAY,
    LG_FLEX_DIRECTION,
    LG_FLEX_GROW,
    LG_GAP,
    LG_PADDING,
    MD_ALIGN_ITEMS,
    MD_DISPLAY,
    MD_FLEX_DIRECTION,
    MD_FLEX_GROW,
    MD_GAP,
    MD_PADDING,
    OVERFLOW,
    PADDING,
    SM_ALIGN_ITEMS,
    SM_DISPLAY,
    SM_FLEX_DIRECTION,
    SM_FLEX_GROW,
    SM_GAP,
    SM_PADDING,
    XL_ALIGN_ITEMS,
    XL_DISPLAY,
    XL_FLEX_DIRECTION,
    XL_FLEX_GROW,
    XL_GAP,
    XL_PADDING,
    XXL_ALIGN_ITEMS,
    XXL_DISPLAY,
    XXL_FLEX_DIRECTION,
    XXL_FLEX_GROW,
    XXL_GAP,
    XXL_PADDING,
} from "@/config/design-tokens.ts";
import { cn } from "@/helpers/cn.ts";
import type { FlexElement, FlexProps } from "./types";

export const Flex = <E extends FlexElement = typeof FLEX_DEFAULT_ELEMENT>({
    as,
    ref,
    overflow,
    display,
    smDisplay,
    mdDisplay,
    lgDisplay,
    xlDisplay,
    xxlDisplay,
    flexDirection,
    smFlexDirection,
    mdFlexDirection,
    lgFlexDirection,
    xlFlexDirection,
    xxlFlexDirection,
    flexWrap,
    flexGrow,
    smFlexGrow,
    mdFlexGrow,
    lgFlexGrow,
    xlFlexGrow,
    xxlFlexGrow,
    flexShrink = 1,
    alignItems,
    smAlignItems,
    mdAlignItems,
    lgAlignItems,
    xlAlignItems,
    xxlAlignItems,
    alignSelf,
    justifyContent,
    gap,
    smGap,
    mdGap,
    lgGap,
    xlGap,
    xxlGap,
    padding = 0,
    smPadding,
    mdPadding,
    lgPadding,
    xlPadding,
    xxlPadding,
    fullWidth,
    smFullWidth,
    mdFullWidth,
    lgFullWidth,
    xlFullWidth,
    xxlFullWidth,
    truncate = false,
    className,
    children,
    ...rest
}: FlexProps<E>) => {
    const Component = (as || FLEX_DEFAULT_ELEMENT) as ElementType;

    return (
        <Component
            className={cn(
                "flex",
                fullWidth && "w-full",
                smFullWidth && "sm:w-full",
                mdFullWidth && "md:w-full",
                lgFullWidth && "lg:w-full",
                xlFullWidth && "xl:w-full",
                xxlFullWidth && "2xl:w-full",
                overflow && OVERFLOW[overflow],
                display && DISPLAY[display],
                smDisplay && SM_DISPLAY[smDisplay],
                mdDisplay && MD_DISPLAY[mdDisplay],
                lgDisplay && LG_DISPLAY[lgDisplay],
                xlDisplay && XL_DISPLAY[xlDisplay],
                xxlDisplay && XXL_DISPLAY[xxlDisplay],
                flexDirection && FLEX_DIRECTION[flexDirection],
                smFlexDirection && SM_FLEX_DIRECTION[smFlexDirection],
                mdFlexDirection && MD_FLEX_DIRECTION[mdFlexDirection],
                lgFlexDirection && LG_FLEX_DIRECTION[lgFlexDirection],
                xlFlexDirection && XL_FLEX_DIRECTION[xlFlexDirection],
                xxlFlexDirection && XXL_FLEX_DIRECTION[xxlFlexDirection],
                flexWrap && FLEX_WRAP[flexWrap],
                flexGrow && FLEX_GROW[flexGrow],
                smFlexGrow && SM_FLEX_GROW[smFlexGrow],
                mdFlexGrow && MD_FLEX_GROW[mdFlexGrow],
                lgFlexGrow && LG_FLEX_GROW[lgFlexGrow],
                xlFlexGrow && XL_FLEX_GROW[xlFlexGrow],
                xxlFlexGrow && XXL_FLEX_GROW[xxlFlexGrow],
                FLEX_SHRINK[flexShrink],
                alignItems && ALIGN_ITEMS[alignItems],
                smAlignItems && SM_ALIGN_ITEMS[smAlignItems],
                mdAlignItems && MD_ALIGN_ITEMS[mdAlignItems],
                lgAlignItems && LG_ALIGN_ITEMS[lgAlignItems],
                xlAlignItems && XL_ALIGN_ITEMS[xlAlignItems],
                xxlAlignItems && XXL_ALIGN_ITEMS[xxlAlignItems],
                alignSelf && ALIGN_SELF[alignSelf],
                justifyContent && JUSTIFY_CONTENT[justifyContent],
                gap && GAP[gap],
                smGap && SM_GAP[smGap],
                mdGap && MD_GAP[mdGap],
                lgGap && LG_GAP[lgGap],
                xlGap && XL_GAP[xlGap],
                xxlGap && XXL_GAP[xxlGap],
                PADDING[padding],
                smPadding && SM_PADDING[smPadding],
                mdPadding && MD_PADDING[mdPadding],
                lgPadding && LG_PADDING[lgPadding],
                xlPadding && XL_PADDING[xlPadding],
                xxlPadding && XXL_PADDING[xxlPadding],
                truncate && "truncate",
                className,
            )}
            {...rest}
        >
            {children}
        </Component>
    );
};
