// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: createUser.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    email,
    password_hash,
    user_role,
    user_name
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	UserRole     string
	UserName     pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.UserRole,
		arg.UserName,
	)
	return err
}
