// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getUserByID.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    email,
    user_role,
    user_name,
    is_active,
    created_at,
    updated_at
FROM users
WHERE id = $1 AND is_active = TRUE
LIMIT 1
`

type GetUserByIDRow struct {
	ID        pgtype.UUID
	Email     string
	UserRole  string
	UserName  pgtype.Text
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UserRole,
		&i.UserName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
