// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getWords.sql

package database

import (
	"context"
)

const getWords = `-- name: GetWords :many
SELECT id, english, russian, difficulty 
FROM words
`

func (q *Queries) GetWords(ctx context.Context) ([]Word, error) {
	rows, err := q.db.Query(ctx, getWords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Word
	for rows.Next() {
		var i Word
		if err := rows.Scan(
			&i.ID,
			&i.English,
			&i.Russian,
			&i.Difficulty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
