// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	UserRole     string
	UserName     pgtype.Text
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Word struct {
	ID         int64
	English    string
	Russian    string
	Difficulty string
}
