// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: createWord.sql

package db

import (
	"context"
)

const createWord = `-- name: CreateWord :exec
INSERT INTO words (
    english,
    russian,
    difficulty
)
VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT DO NOTHING
`

type CreateWordParams struct {
	English    string
	Russian    string
	Difficulty string
}

func (q *Queries) CreateWord(ctx context.Context, arg CreateWordParams) error {
	_, err := q.db.Exec(ctx, createWord, arg.English, arg.Russian, arg.Difficulty)
	return err
}
